### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by hryanjones** [anvaka/streak#2]
This is low priority and feel free to say that this can wait to later, but I thought it'd be fun to have a fav-icon.
I didn't see a lot of colors on the site, so I stole the link-green.
When thinking of someone being "on a streak" I also think of them "being on fire", so I stole [this fireball SVG](http://www.clawarinvestigation.com/img/fireball-icon.svg) and goofed around with it and added an S over the top. Attached a png, but the source is an SVG:

![streak-fav-icon-idea svg](https://cloud.githubusercontent.com/assets/2705396/24592189/3c111dd2-17c7-11e7-85a5-bb3b210b103e.png)

**Comment by anvaka** [comment]
Thank you!
